// Frases correctas organizadas por nivel
const frasesPorNivel = {
  1: [
    "el tren",
    "la nube",
    "una flor",
    "un lápiz",
    "el libro",
    "la silla",
    "una botella",
    "un pez",
    "la guitarra",
    "el río",
    "una casa",
    "un perro",
    "la luna",
    "el pan",
    "una lámpara",
    "un tambor",
    "la caja",
    "el motor",
    "una chaqueta",
    "un árbol",
    "la roca",
    "el puente",
    "una carta",
    "un tambor",
    "la planta",
    "el dron",
    "una puerta",
    "el volcán",
    "la espada",
    "una mesa",
    "un cuchillo",
    "el sombrero",
    "la cocina",
    "una estrella",
    "el sofá",
    "un castillo",
    "el zapato",
    "la ventana",
    "una mochila",
    "el espejo",
    "la caña",
    "un banco",
    "el fuego",
    "una nube",
    "la piedra",
    "un camión",
    "el reloj",
    "una taza",
    "el piano",
    "una calle",
    "el teclado"
  ],
  2: [
    "el tren largo",
    "la nube gris",
    "una flor azul",
    "un lápiz nuevo",
    "el libro abierto",
    "la silla cómoda",
    "una botella vacía",
    "un pez dorado",
    "la guitarra afinada",
    "el río caudaloso",
    "una casa antigua",
    "un perro grande",
    "la luna llena",
    "el pan caliente",
    "una lámpara encendida",
    "un tambor ruidoso",
    "la caja pesada",
    "el motor ruidoso",
    "una chaqueta mojada",
    "un árbol alto",
    "la roca dura",
    "el puente colgante",
    "una carta larga",
    "un tambor africano",
    "la planta verde",
    "el dron silencioso",
    "una puerta abierta",
    "el volcán activo",
    "la espada afilada",
    "una mesa redonda",
    "un cuchillo oxidado",
    "el sombrero viejo",
    "la cocina sucia",
    "una estrella brillante",
    "el sofá amplio",
    "un castillo medieval",
    "el zapato sucio",
    "la ventana rota",
    "una mochila ligera",
    "el espejo roto",
    "la caña delgada",
    "un banco vacío",
    "el fuego vivo",
    "una nube espesa",
    "la piedra lisa",
    "un camión grande",
    "el reloj digital",
    "una taza rota",
    "el piano desafinado",
    "una calle estrecha",
    "el teclado limpio"
  ],
  3: [
    "el viejo tren oxidado",
    "la blanca nube densa",
    "una delicada flor silvestre",
    "un pequeño lápiz roto",
    "el antiguo libro polvoriento",
    "la cómoda silla de madera",
    "una vacía botella plástica",
    "un veloz pez plateado",
    "la afinada guitarra clásica",
    "el caudaloso río bravo",
    "una antigua casa rural",
    "un enorme perro dormido",
    "la brillante luna redonda",
    "el caliente pan recién hecho",
    "una encendida lámpara roja",
    "un grande tambor africano",
    "la pesada caja de metal",
    "el ruidoso motor viejo",
    "una mojada chaqueta azul",
    "un alto árbol seco",
    "la dura roca negra",
    "el colgante puente inestable",
    "una larga carta triste",
    "un africano tambor rústico",
    "la verde planta colgante",
    "el silencioso dron gris",
    "una abierta puerta rota",
    "el activo volcán humeante",
    "la afilada espada curva",
    "una redonda mesa blanca",
    "un oxidado cuchillo corto",
    "el viejo sombrero roto",
    "la sucia cocina abandonada",
    "una brillante estrella fugaz",
    "el amplio sofá azul",
    "un medieval castillo abandonado",
    "el sucio zapato roto",
    "la rota ventana sucia",
    "una ligera mochila deportiva",
    "el roto espejo viejo",
    "la delgada caña larga",
    "un vacío banco urbano",
    "el vivo fuego rojo",
    "una espesa nube blanca",
    "la lisa piedra redonda",
    "un grande camión amarillo",
    "el digital reloj moderno",
    "una rota taza blanca",
    "el desafinado piano antiguo",
    "una estrecha calle oscura",
    "el limpio teclado blanco"
  ],
  4: [
    "el tren llega temprano",
    "la nube cubre el cielo",
    "una flor crece sola",
    "un lápiz escribe suave",
    "el libro brilla nuevo",
    "la silla gira rápido",
    "una botella cae fuerte",
    "un pez nada tranquilo",
    "la guitarra suena dulce",
    "el río corre rápido",
    "una casa parece vieja",
    "un perro ladra fuerte",
    "la luna ilumina suave",
    "el pan huele rico",
    "una lámpara alumbra bien",
    "un tambor suena fuerte",
    "la caja pesa mucho",
    "el motor ruge fuerte",
    "una chaqueta abriga bien",
    "un árbol crece alto",
    "la roca parece sólida",
    "el puente cruza ancho",
    "una carta llega rápido",
    "un tambor marca ritmo",
    "la planta crece verde",
    "el dron vuela alto",
    "una puerta abre fácil",
    "el volcán arroja lava",
    "la espada corta fuerte",
    "una mesa sostiene libros",
    "un cuchillo corta pan",
    "el sombrero cubre cabeza",
    "la cocina huele rico",
    "una estrella brilla lejos",
    "el sofá es cómodo",
    "un castillo parece antiguo",
    "el zapato está sucio",
    "la ventana está abierta",
    "una mochila pesa poco",
    "el espejo refleja imagen",
    "la caña sostiene el peso",
    "un banco espera gente",
    "el fuego calienta casa",
    "una nube cambia forma",
    "la piedra es lisa",
    "un camión pasa rápido",
    "el reloj marca tiempo",
    "una taza está vacía",
    "el piano suena fuerte",
    "una calle está vacía",
    "el teclado funciona bien"
  ],
  5: [
    "el viejo tren de hierro oxidado",
    "la blanca nube gris cubre cielo",
    "una delicada flor silvestre crece sola",
    "un pequeño lápiz roto escribe suave",
    "el antiguo libro polvoriento brilla nuevo",
    "la cómoda silla de madera gira rápido",
    "una vacía botella plástica cae fuerte",
    "un veloz pez plateado nada tranquilo",
    "la afinada guitarra clásica suena dulce",
    "el caudaloso río bravo corre rápido",
    "una antigua casa rural parece vieja",
    "un enorme perro dormido ladra fuerte",
    "la brillante luna redonda ilumina suave",
    "el caliente pan recién hecho huele rico",
    "una encendida lámpara roja alumbra bien",
    "un grande tambor africano suena fuerte",
    "la pesada caja de metal pesa mucho",
    "el ruidoso motor viejo ruge fuerte",
    "una mojada chaqueta azul abriga bien",
    "un alto árbol seco crece" ,
    "el viejo tren de hierro oxidado",
    "la blanca nube gris cubre cielo",
    "una delicada flor silvestre crece sola",
    "un pequeño lápiz roto escribe suave",
    "el antiguo libro polvoriento brilla nuevo",
    "la cómoda silla de madera gira rápido",
    "una vacía botella plástica cae fuerte",
    "un veloz pez plateado nada tranquilo",
    "la afinada guitarra clásica suena dulce",
    "el caudaloso río bravo corre rápido",
    "una antigua casa rural parece vieja",
    "un enorme perro dormido ladra fuerte",
    "la brillante luna redonda ilumina suave",
    "el caliente pan recién hecho huele rico",
    "una encendida lámpara roja alumbra bien",
    "un grande tambor africano suena fuerte",
    "la pesada caja de metal pesa mucho",
    "el ruidoso motor viejo ruge fuerte",
    "una mojada chaqueta azul abriga bien",
    "un alto árbol seco crece alto",
    "la dura roca negra parece sólida",
    "el colgante puente inestable cruza ancho",
    "una larga carta triste llega rápido",
    "un africano tambor rústico marca ritmo",
    "la verde planta colgante crece verde",
    "el silencioso dron gris vuela alto",
    "una abierta puerta rota abre fácil",
    "el activo volcán humeante arroja lava",
    "la afilada espada curva corta fuerte",
    "una redonda mesa blanca sostiene libros",
    "un oxidado cuchillo corto corta pan",
    "el viejo sombrero roto cubre cabeza",
    "la sucia cocina abandonada huele rico",
    "una brillante estrella fugaz brilla lejos",
    "el amplio sofá azul es cómodo",
    "un medieval castillo abandonado parece antiguo",
    "el sucio zapato roto está sucio",
    "la rota ventana sucia está abierta",
    "una ligera mochila deportiva pesa poco",
    "el roto espejo viejo refleja imagen",
    "la delgada caña larga sostiene el peso",
    "un vacío banco urbano espera gente",
    "el vivo fuego rojo calienta casa",
    "una espesa nube blanca cambia forma",
    "la lisa piedra redonda es sólida",
    "un grande camión amarillo pasa rápido",
    "el moderno reloj digital marca tiempo",
    "una vieja taza rota está vacía",
    "el desafinado piano antiguo suena fuerte",
    "una estrecha calle oscura está vacía",
    "el limpio teclado blanco funciona bien"
  ]
};
